name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Tar all files
      run: tar -zcf /tmp/nmpQkGecWh.tar.gz dist/AutoCadDrawings dist/CSVs dist/WeatherIcon dist/assets dist/images dist/index.html

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no /tmp/nmpQkGecWh.tar.gz user@157.173.216.152:/path/to/destination
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
